spring.application.name=labwork-2

# Database Configuration / ???????????? ???? ?????
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_management_db
spring.datasource.username=user_db
spring.datasource.password=useruser
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration / ???????????? JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator Configuration / ???????????? Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
